using System.Web;

namespace UMD.Core.Platforms;

/// <summary>
/// Utilitarios de URL.
///
/// Porte de clean_url() e is_playlist_url() de ultimate_downloader.py, com uma
/// correcao importante: o original tratava qualquer "list=" como playlist
/// normal. As playlists automaticas do YouTube (radio e mix, prefixo RD, RDMM,
/// RDCLAK, UL, LL) sao geradas sob demanda e nao tem fim, entao consultar item
/// por item nunca termina.
/// </summary>
public static class UrlHelper
{
    /// <summary>
    /// Prefixos de playlists geradas automaticamente pelo YouTube.
    /// RD*     = radio / mix
    /// UL*     = lista temporaria de upload
    /// LL      = "curtidos" do proprio usuario
    /// </summary>
    private static readonly string[] AutoPlaylistPrefixes = ["RD", "UL", "LL"];

    /// <summary>A URL aponta para uma playlist de verdade, com itens finitos?</summary>
    public static bool IsRealPlaylist(string url)
    {
        var id = GetPlaylistId(url);
        return id is not null && !IsAutoGeneratedPlaylist(id);
    }

    /// <summary>A URL carrega uma playlist automatica (radio/mix) sem fim definido?</summary>
    public static bool IsAutoGeneratedPlaylist(string playlistId) =>
        AutoPlaylistPrefixes.Any(p => playlistId.StartsWith(p, StringComparison.OrdinalIgnoreCase));

    /// <summary>A URL tem um parametro de playlist, de qualquer tipo?</summary>
    public static bool HasPlaylistParameter(string url) => GetPlaylistId(url) is not null;

    /// <summary>Le o valor de "list" da query string, se houver.</summary>
    public static string? GetPlaylistId(string url)
    {
        if (!Uri.TryCreate(Normalize(url), UriKind.Absolute, out var uri)) return null;

        var value = HttpUtility.ParseQueryString(uri.Query)["list"];
        return string.IsNullOrWhiteSpace(value) ? null : value;
    }

    /// <summary>
    /// Remove os parametros de playlist, deixando so o video.
    /// Tambem tira lixo de rastreamento que alguns compartilhamentos colam.
    /// </summary>
    public static string StripPlaylist(string url)
    {
        if (!Uri.TryCreate(Normalize(url), UriKind.Absolute, out var uri)) return url;

        var query = HttpUtility.ParseQueryString(uri.Query);
        foreach (var key in new[] { "list", "start_radio", "index", "pp", "si", "feature" })
            query.Remove(key);

        var builder = new UriBuilder(uri) { Query = query.ToString() };
        return builder.Uri.ToString();
    }

    private static string Normalize(string url)
    {
        var u = (url ?? string.Empty).Trim();
        return u.Contains("://", StringComparison.Ordinal) ? u : "https://" + u;
    }
}