using System.Text;
using UMD.Core.Configuration;
using UMD.Core.Engine;
using UMD.Core.Models;
using UMD.Core.Platforms;
using UMD.Core.Tools;

// Programa de teste do motor. Nao faz parte do app final: serve so para
// verificar, no seu Windows, que a Fase 1 funciona de ponta a ponta.

Console.OutputEncoding = Encoding.UTF8;
Console.WriteLine("=== UMD .NET - teste do motor ===\n");

// ---------------------------------------------------------------------------
// 1. Verificar os binarios externos
// ---------------------------------------------------------------------------

var tools = new ToolManager();
var status = tools.CheckAll();

Console.WriteLine($"yt-dlp : {status.YtDlpPath ?? "NAO ENCONTRADO"}");
Console.WriteLine($"ffmpeg : {status.FfmpegPath ?? "NAO ENCONTRADO"}");
Console.WriteLine($"deno   : {status.DenoPath ?? "NAO ENCONTRADO"}");

if (!status.IsUsable)
{
    Console.WriteLine();
    Console.WriteLine(status.Describe());
    Console.WriteLine("Rode o script tools\\get-tools.ps1 e tente de novo.");
    return 1;
}

var version = await tools.GetYtDlpVersionAsync();
Console.WriteLine($"versao : {version ?? "nao respondeu"}");

if (!status.HasFfmpeg)
    Console.WriteLine("\nAviso: sem ffmpeg, so da para baixar arquivos que ja vem prontos.");

if (!status.HasDeno)
{
    Console.WriteLine();
    Console.WriteLine("AVISO: deno.exe nao encontrado.");
    Console.WriteLine("Desde o yt-dlp 2025.11.12 o YouTube exige um runtime de JavaScript");
    Console.WriteLine("para resolver os desafios de assinatura. Sem ele o YouTube responde");
    Console.WriteLine("'This video is not available'. Os outros sites nao sao afetados.");
    Console.WriteLine("Rode tools\\get-tools.ps1 para instalar.");
}

// ---------------------------------------------------------------------------
// 2. Pedir a URL
// ---------------------------------------------------------------------------

Console.WriteLine();
Console.Write("URL (Enter usa um video de teste): ");
var url = Console.ReadLine()?.Trim();

if (string.IsNullOrWhiteSpace(url))
    url = "https://www.youtube.com/watch?v=aqz-KE-bpKQ"; // Big Buck Bunny, livre

if (!PlatformDetector.IsValidUrl(url))
{
    Console.WriteLine("URL invalida.");
    return 1;
}

var platform = PlatformDetector.Detect(url);
Console.WriteLine($"Plataforma detectada: {PlatformDetector.GetDisplayName(platform)}");
Console.WriteLine($"Estrategia: {PlatformDetector.GetStrategy(platform)}");

// ---------------------------------------------------------------------------
// 2b. Decidir o que fazer com o parametro de playlist
// ---------------------------------------------------------------------------

var noPlaylist = false;

if (UrlHelper.GetPlaylistId(url) is { } listId)
{
    if (UrlHelper.IsAutoGeneratedPlaylist(listId))
    {
        // Radio/mix do YouTube: gerada sob demanda, sem fim. Tratar como video
        // unico e a unica opcao sensata.
        Console.WriteLine($"\nA URL contem uma radio automatica do YouTube (list={listId}).");
        Console.WriteLine("Essa lista nao tem fim, entao vou baixar apenas o video.");
        noPlaylist = true;
    }
    else
    {
        Console.WriteLine($"\nA URL contem a playlist {listId}.");
        Console.Write("Baixar a playlist inteira? [s/N]: ");
        noPlaylist = !string.Equals(Console.ReadLine()?.Trim(), "s", StringComparison.OrdinalIgnoreCase);
    }
}

var engine = new YtDlpEngine(tools);

// ---------------------------------------------------------------------------
// 3. Ler os metadados
// ---------------------------------------------------------------------------

Console.Write("\nBuscando metadados");

// Timeout de seguranca: sem isto, um extractor lento trava o programa em
// silencio e nao da para saber se esta trabalhando ou parado.
using var infoCts = new CancellationTokenSource(TimeSpan.FromSeconds(90));

var ticker = Task.Run(async () =>
{
    var started = DateTime.UtcNow;
    while (!infoCts.IsCancellationRequested)
    {
        try { await Task.Delay(1000, infoCts.Token); } catch (OperationCanceledException) { break; }
        Console.Write($"\rBuscando metadados... {(DateTime.UtcNow - started).TotalSeconds:0}s ");
    }
});

MediaInfo? info;
try
{
    info = await engine.GetInfoAsync(url, flatPlaylist: true, noPlaylist: noPlaylist, ct: infoCts.Token);
}
catch (OperationCanceledException)
{
    Console.WriteLine("\nO yt-dlp passou de 90 segundos sem responder. Consulta abortada.");
    Console.WriteLine("Isso costuma indicar uma playlist muito grande ou um site lento.");
    return 1;
}
catch (YtDlpException ex)
{
    Console.WriteLine($"\nFalhou: {ex.Message}");
    return 1;
}
finally
{
    infoCts.Cancel();
    try { await ticker; } catch (OperationCanceledException) { /* esperado */ }
    Console.WriteLine();
}

if (info is null)
{
    Console.WriteLine("O yt-dlp nao devolveu nada.");
    return 1;
}

Console.WriteLine($"  Titulo   : {info.Title}");
Console.WriteLine($"  Autor    : {info.Uploader ?? info.Channel ?? "-"}");
Console.WriteLine($"  Duracao  : {info.FormatDuration()}");
Console.WriteLine($"  Formatos : {info.Formats.Count}");
Console.WriteLine($"  Playlist : {(info.IsPlaylist ? $"sim ({info.Entries.Count} itens)" : "nao")}");

Console.WriteLine("\n  5 melhores formatos:");
foreach (var f in info.GetDisplayableFormats().Take(5))
{
    var size = f.EffectiveSize is { } s ? DownloadProgress.FormatBytes(s) : "tamanho desconhecido";
    Console.WriteLine($"    [{f.FormatId,-6}] {f.ToDisplayString(),-34} {size}");
}

// ---------------------------------------------------------------------------
// 4. Escolher o modo
// ---------------------------------------------------------------------------

Console.WriteLine("\n  1) Video 720p");
Console.WriteLine("  2) Video na melhor qualidade");
Console.WriteLine("  3) Somente audio (MP3 320k)");
Console.WriteLine("  4) So ver o comando, sem baixar");
Console.Write("\nEscolha [1]: ");

var choice = Console.ReadLine()?.Trim();

var settings = AppSettings.Load();
var baseRequest = choice switch
{
    "2" => settings.CreateRequest(url, audioOnly: false, quality: VideoQuality.Best),
    "3" => settings.CreateRequest(url, audioOnly: true),
    _   => settings.CreateRequest(url, audioOnly: false, quality: VideoQuality.Q720p)
};

// DownloadRequest usa propriedades init-only, entao a escolha de playlist entra
// via "with" em vez de mutacao.
var request = baseRequest with { DownloadPlaylist = !noPlaylist };

Console.WriteLine($"\nPasta de saida: {request.OutputDirectory}");

if (choice == "4")
{
    Console.WriteLine("\nComando que seria executado:\n");
    Console.WriteLine($"  \"{tools.YtDlpPath}\" " +
        string.Join(" ", engine.BuildDownloadArguments(request).Select(Quote)));
    return 0;
}

// ---------------------------------------------------------------------------
// 5. Baixar, com Ctrl+C cancelando de forma limpa
// ---------------------------------------------------------------------------

using var cts = new CancellationTokenSource();
Console.CancelKeyPress += (_, e) =>
{
    e.Cancel = true;
    Console.WriteLine("\nCancelando...");
    cts.Cancel();
};

Console.WriteLine("\nBaixando (Ctrl+C cancela):\n");

var progress = new Progress<DownloadProgress>(p =>
{
    var pct = p.Percent is { } v ? $"{v,5:0.0}%" : "  ??%";
    var of = p.TotalBytes is { } t
        ? $"{DownloadProgress.FormatBytes(p.DownloadedBytes)} / {DownloadProgress.FormatBytes(t)}"
        : DownloadProgress.FormatBytes(p.DownloadedBytes);

    // Video em alta qualidade vem em DASH: faixa 1 = video, faixa 2 = audio.
    // Mostrar o acumulado deixa claro que a barra nao "voltou" sozinha.
    var parte = $"faixa {p.PartIndex}";
    var total = p.PreviousPartsBytes > 0
        ? $"  [total {DownloadProgress.FormatBytes(p.TotalDownloadedBytes)}]"
        : string.Empty;

    Console.Write($"\r  {parte}  {pct}  {of,-24}  {p.FormatSpeed(),-12}  ETA {p.FormatEta(),-8}{total}   ");
});

var result = await engine.DownloadAsync(request, progress, cts.Token);
Console.WriteLine("\n");

if (result.Success)
{
    Console.WriteLine("Concluido.");
    foreach (var path in result.FilePaths)
        Console.WriteLine($"  {path}");

    if (result.FilePaths.Count == 0)
        Console.WriteLine("  (nenhum caminho capturado - verifique a pasta de saida)");

    // Conferencia explicita: o caminho reportado tem que existir no disco.
    foreach (var path in result.FilePaths)
    {
        var existe = File.Exists(path);
        var tam = existe ? DownloadProgress.FormatBytes(new FileInfo(path).Length) : "-";
        Console.WriteLine($"    existe: {existe,-5}  tamanho: {tam,-12}  ext: {Path.GetExtension(path)}");
    }

    return 0;
}

Console.WriteLine($"Falhou: {result.ErrorMessage}");
Console.WriteLine("\nUltimas linhas da saida do yt-dlp:");
foreach (var line in (result.RawOutput ?? "").Split('\n').TakeLast(15))
    Console.WriteLine($"  {line.TrimEnd()}");

return 1;

static string Quote(string arg) => arg.Contains(' ') ? $"\"{arg}\"" : arg;